import React, { useState, useMemo, useEffect } from 'react';
import {
  auth,
  signOut,
  db,
  collection,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  onSnapshot,
  query,
  orderBy,
  getDoc,
  setDoc
} from './firebase';
import { useAuth } from './hooks/useAuth';
import ProtectedRoute from './components/ProtectedRoute';
import OrderForm from './components/OrderForm';
import MenuManager from './components/MenuManager';
import SalesReports from './components/SalesReports';

interface CakeItem {
  id: string;
  name: string;
  basePrice: number;
}

interface Order {
  id: string;
  customerName: string;
  itemName: string;
  quantity: number;
  total: number;
  notes: string;
  source: string;
  timestamp: string;
  pickupDate: string;
  pickupTime: string;
  status: 'pending' | 'completed';
}

type SortOption = 'earliest-pickup' | 'latest-pickup';
type FilterOption = 'today' | 'pending' | 'completed' | 'summary';

// Helper for consistent local date string generation
const getLocalDateStr = (date: Date = new Date()) => {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
};

const Dashboard: React.FC = () => {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<'orders' | 'menu' | 'reports'>('orders');
  const [isOrderFormOpen, setIsOrderFormOpen] = useState(false);
  const [editingOrder, setEditingOrder] = useState<Order | null>(null);

  // State is now managed via Firestore listeners
  const [menu, setMenu] = useState<CakeItem[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);

  const [orderToComplete, setOrderToComplete] = useState<string | null>(null);
  const [orderToDelete, setOrderToDelete] = useState<string | null>(null);

  const [filter, setFilter] = useState<FilterOption>('today');
  const [sortBy, setSortBy] = useState<SortOption>('earliest-pickup');

  // Order Summary State
  const [summaryDate, setSummaryDate] = useState(() => getLocalDateStr());

  // New Effect: Ensure User Profile Exists
  useEffect(() => {
    if (!user) return;

    const ensureUserProfile = async () => {
      try {
        const userDocRef = doc(db, 'users', user.uid);
        const userSnapshot = await getDoc(userDocRef);

        if (!userSnapshot.exists()) {
          await setDoc(userDocRef, {
            uid: user.uid,
            fullName: user.displayName || 'Guest User',
            email: user.email || '',
            createdAt: new Date().toISOString(),
            role: 'user'
          });
          console.log("User profile created automatically.");
        }
      } catch (error) {
        console.error("Error verifying user profile:", error);
      }
    };

    ensureUserProfile();
  }, [user]);

  // Firestore Listener for Menu
  useEffect(() => {
    if (!user) return;

    const q = query(collection(db, 'users', user.uid, 'menu'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const menuData = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as CakeItem[];
      setMenu(menuData);
    });

    return () => unsubscribe();
  }, [user]);

  // Firestore Listener for Orders
  useEffect(() => {
    if (!user) return;

    const q = query(
      collection(db, 'users', user.uid, 'orders'),
      orderBy('timestamp', 'desc')
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const orderData = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as Order[];
      setOrders(orderData);
    });

    return () => unsubscribe();
  }, [user]);

  const handleLogout = async () => {
    try {
      await signOut(auth);
    } catch (error) {
      console.error("Logout failed", error);
    }
  };

  const handleOrderSubmit = async (data: any) => {
    if (!user) return;

    try {
      if (editingOrder) {
        // Update existing order
        const orderRef = doc(db, 'users', user.uid, 'orders', editingOrder.id);
        await updateDoc(orderRef, data);
        setEditingOrder(null);
      } else {
        // Create new order
        // Note: ID is generated by Firestore
        await addDoc(collection(db, 'users', user.uid, 'orders'), {
          ...data,
          status: 'pending'
        });
      }
      setIsOrderFormOpen(false);
    } catch (error) {
      console.error("Error saving order:", error);
      alert("Failed to save order. Please try again.");
    }
  };

  const handleDuplicateOrder = async (order: Order) => {
    if (!user) return;
    try {
      const { id, ...orderData } = order;
      await addDoc(collection(db, 'users', user.uid, 'orders'), {
        ...orderData,
        status: 'pending',
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      console.error("Error duplicating order:", error);
    }
  };

  const confirmComplete = async () => {
    if (orderToComplete && user) {
      try {
        const orderRef = doc(db, 'users', user.uid, 'orders', orderToComplete);
        await updateDoc(orderRef, { status: 'completed' });
        setOrderToComplete(null);
      } catch (error) {
        console.error("Error completing order:", error);
      }
    }
  };

  const confirmDelete = async () => {
    if (orderToDelete && user) {
      try {
        const orderRef = doc(db, 'users', user.uid, 'orders', orderToDelete);
        await deleteDoc(orderRef);
        setOrderToDelete(null);
      } catch (error) {
        console.error("Error deleting order:", error);
      }
    }
  };

  const toggleOrderStatus = async (id: string) => {
    if (!user) return;

    const order = orders.find(o => o.id === id);
    if (!order) return;

    if (order.status === 'pending') {
      setOrderToComplete(id);
    } else {
      // Re-open
      try {
        const orderRef = doc(db, 'users', user.uid, 'orders', id);
        await updateDoc(orderRef, { status: 'pending' });
      } catch (error) {
        console.error("Error re-opening order:", error);
      }
    }
  };

  const handleEditOrder = (order: Order) => {
    setEditingOrder(order);
    setIsOrderFormOpen(true);
  };

  const handleAddMenuItem = async (item: CakeItem) => {
    if (!user) return;
    try {
      // We exclude the ID generated by the UI to let Firestore generate one
      const { id, ...data } = item;
      await addDoc(collection(db, 'users', user.uid, 'menu'), data);
    } catch (error) {
      console.error("Error adding menu item:", error);
    }
  };

  const handleRemoveMenuItem = async (id: string) => {
    if (!user) return;
    try {
      await deleteDoc(doc(db, 'users', user.uid, 'menu', id));
    } catch (error) {
      console.error("Error removing menu item:", error);
    }
  };

  const handleUpdateMenuItem = async (updatedItem: CakeItem) => {
    if (!user) return;
    try {
      const { id, ...data } = updatedItem;
      await updateDoc(doc(db, 'users', user.uid, 'menu', id), data as any);
    } catch (error) {
      console.error("Error updating menu item:", error);
    }
  };

  const getDayName = (dateString: string) => {
    if (!dateString) return '';
    const [year, month, day] = dateString.split('-').map(Number);
    const date = new Date(year, month - 1, day);
    return date.toLocaleDateString('en-US', { weekday: 'long' }).toUpperCase();
  };

  // Summary Logic
  const summaryStats = useMemo(() => {
    const stats: Record<string, number> = {};
    orders.forEach(o => {
      if (o.pickupDate === summaryDate) {
        const key = o.itemName;
        stats[key] = (stats[key] || 0) + (o.quantity || 0);
      }
    });
    return Object.entries(stats).sort((a, b) => b[1] - a[1]);
  }, [orders, summaryDate]);

  const processedOrders = useMemo(() => {
    let result = [...orders];

    // Fix timezone issue: use local date instead of UTC via helper
    const todayStr = getLocalDateStr();

    // Filter logic
    if (filter === 'today') {
      result = result.filter(o => o.pickupDate === todayStr && o.status === 'pending');
    } else if (filter === 'summary') {
      return [];
    } else {
      result = result.filter(o => o.status === (filter as 'pending' | 'completed'));
    }

    // Sort logic
    result.sort((a, b) => {
      const timeA = a.pickupTime || '00:00';
      const timeB = b.pickupTime || '00:00';
      const dateA = new Date(`${a.pickupDate}T${timeA}`);
      const dateB = new Date(`${b.pickupDate}T${timeB}`);

      switch (sortBy) {
        case 'earliest-pickup': return dateA.getTime() - dateB.getTime();
        case 'latest-pickup': return dateB.getTime() - dateA.getTime();
        default: return 0;
      }
    });
    return result;
  }, [orders, filter, sortBy]);

  // Grouping Logic: Assign colors to customers with multiple orders
  const customerColorMap = useMemo(() => {
    const counts: Record<string, number> = {};

    // Count occurrences of each customer name
    processedOrders.forEach(o => {
      if (o.customerName?.trim()) {
        const name = o.customerName.trim();
        counts[name] = (counts[name] || 0) + 1;
      }
    });

    const multiOrderCustomers = Object.keys(counts).filter(name => counts[name] > 1);

    // Premium pastel palette
    const palette = [
      'bg-emerald-50 border-emerald-200',
      'bg-blue-50 border-blue-200',
      'bg-orange-50 border-orange-200',
      'bg-purple-50 border-purple-200',
      'bg-pink-50 border-pink-200',
      'bg-cyan-50 border-cyan-200',
    ];

    const map: Record<string, string> = {};
    multiOrderCustomers.forEach((name, index) => {
      map[name] = palette[index % palette.length];
    });

    return map;
  }, [processedOrders]);

  return (
    <div className="min-h-screen bg-[#FDFDFD] text-slate-900 selection:bg-indigo-50 pb-32 md:pb-12">
      <OrderForm
        isOpen={isOrderFormOpen}
        onClose={() => {
          setIsOrderFormOpen(false);
          setEditingOrder(null);
        }}
        onSubmit={handleOrderSubmit}
        menu={menu}
        initialData={editingOrder}
      />

      {/* Confirmation Modal for Completing Order */}
      {orderToComplete && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={() => setOrderToComplete(null)} />
          <div className="relative w-full max-w-xs bg-white p-8 rounded-[2rem] shadow-2xl border border-slate-100 text-center animate-in zoom-in-95">
            <div className="w-16 h-16 bg-emerald-50 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-emerald-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7" /></svg>
            </div>
            <h3 className="font-black text-slate-900 text-lg">Finish Order?</h3>
            <p className="text-slate-400 text-xs font-bold mt-1">This will move the order to completed.</p>
            <div className="flex gap-3 mt-6">
              <button onClick={() => setOrderToComplete(null)} className="flex-1 py-3 bg-slate-100 text-slate-500 rounded-xl font-bold text-xs uppercase tracking-widest">No</button>
              <button onClick={confirmComplete} className="flex-1 py-3 bg-emerald-500 text-white rounded-xl font-bold text-xs uppercase tracking-widest shadow-lg shadow-emerald-100">Yes, Done</button>
            </div>
          </div>
        </div>
      )}

      {/* Confirmation Modal for Deleting Order */}
      {orderToDelete && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={() => setOrderToDelete(null)} />
          <div className="relative w-full max-w-xs bg-white p-8 rounded-[2rem] shadow-2xl border border-slate-100 text-center animate-in zoom-in-95">
            <div className="w-16 h-16 bg-rose-50 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-rose-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
            </div>
            <h3 className="font-black text-slate-900 text-lg">Delete Order?</h3>
            <p className="text-slate-400 text-xs font-bold mt-1">This action cannot be undone.</p>
            <div className="flex gap-3 mt-6">
              <button onClick={() => setOrderToDelete(null)} className="flex-1 py-3 bg-slate-100 text-slate-500 rounded-xl font-bold text-xs uppercase tracking-widest">Cancel</button>
              <button onClick={confirmDelete} className="flex-1 py-3 bg-rose-500 text-white rounded-xl font-bold text-xs uppercase tracking-widest shadow-lg shadow-rose-100">Delete</button>
            </div>
          </div>
        </div>
      )}

      <nav className="bg-white/80 backdrop-blur-md sticky top-0 z-50 border-b border-slate-100">
        <div className="max-w-5xl mx-auto px-4 sm:px-6">
          <div className="flex justify-between h-16 items-center">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
                <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                </svg>
              </div>
              <span className="font-bold tracking-tight text-lg">OrderTaker</span>
            </div>

            <div className="flex items-center gap-3 sm:gap-4">
              <div className="hidden sm:flex items-center gap-4 md:gap-6">
                <button
                  onClick={() => setActiveTab('orders')}
                  className={`text-sm font-bold transition-all ${activeTab === 'orders' ? 'text-indigo-600' : 'text-slate-400 hover:text-slate-600'}`}
                >
                  Live Orders
                </button>
                <button
                  onClick={() => setActiveTab('menu')}
                  className={`text-sm font-bold transition-all ${activeTab === 'menu' ? 'text-indigo-600' : 'text-slate-400 hover:text-slate-600'}`}
                >
                  Menu
                </button>
                <button
                  onClick={() => setActiveTab('reports')}
                  className={`text-sm font-bold transition-all ${activeTab === 'reports' ? 'text-indigo-600' : 'text-slate-400 hover:text-slate-600'}`}
                >
                  Sales
                </button>
              </div>

              <div className="h-4 w-px bg-slate-200 hidden sm:block"></div>

              <button
                onClick={handleLogout}
                className="text-slate-400 hover:text-rose-500 transition-colors p-1"
                title="Sign Out"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path fillRule="evenodd" d="M3 12a1 1 0 011-1h13.586l-2.293-2.293a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L17.586 13H4a1 1 0 01-1-1z" clipRule="evenodd" transform="rotate(180 12 12)" />
                  <path d="M16 5a1 1 0 011 1v12a1 1 0 01-1 1h-5a1 1 0 110-2h4V7h-4a1 1 0 110-2h5z" transform="translate(4, 0)" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto py-8 sm:py-10 px-4 sm:px-6">
        {activeTab === 'orders' ? (
          <div className="animate-in fade-in slide-in-from-bottom-2 duration-700">
            <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-6 border-b border-slate-100/50 pb-8">
              <div className="space-y-1">
                <h1 className="text-3xl sm:text-4xl font-black tracking-tighter text-slate-900 drop-shadow-sm">
                  Today's Queue
                </h1>
                <p className="text-slate-400 text-sm font-medium flex items-center gap-2 mt-1">
                  <span className="flex h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  {orders.length} {orders.length === 1 ? 'order' : 'orders'} total
                </p>
              </div>
              <button
                onClick={() => setIsOrderFormOpen(true)}
                className="w-full sm:w-auto bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-4 rounded-xl font-bold text-sm shadow-xl shadow-indigo-100 transition-all active:scale-95 flex items-center justify-center gap-2 border-b-4 border-indigo-800"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M12 4v16m8-8H4" /></svg>
                <span>New Order</span>
              </button>
            </div>

            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 sm:gap-0 mt-10 mb-8">
              <div className="flex items-center gap-3 pb-2 sm:pb-0 overflow-x-auto scrollbar-hide -mx-6 px-6 sm:mx-0 sm:px-0">
                {(['today', 'pending', 'completed', 'summary'] as FilterOption[]).map((f) => (
                  <button
                    key={f}
                    onClick={() => setFilter(f)}
                    className={`whitespace-nowrap px-6 py-3 rounded-xl font-bold text-xs transition-all ${filter === f
                        ? 'bg-white text-indigo-600 shadow-sm border-b-2 border-indigo-600'
                        : 'text-slate-400 hover:text-slate-600'
                      }`}
                  >
                    {f === 'summary' ? 'Order Summary' : f.charAt(0).toUpperCase() + f.slice(1)}
                  </button>
                ))}
              </div>

              {filter !== 'summary' && (
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-black uppercase text-slate-300 tracking-widest">Sort by</span>
                  <select
                    value={sortBy}
                    onChange={(e) => setSortBy(e.target.value as SortOption)}
                    className="bg-transparent text-xs font-bold text-slate-600 outline-none cursor-pointer hover:text-indigo-600 transition-colors"
                  >
                    <option value="earliest-pickup">Earliest Pickup</option>
                    <option value="latest-pickup">Latest Pickup</option>
                  </select>
                </div>
              )}
            </div>

            {filter === 'summary' ? (
              /* Order Summary Widget View */
              <div className="bg-white p-6 rounded-[2rem] border border-slate-100 shadow-sm mb-8 animate-in fade-in slide-in-from-top-4">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-4">
                  <div>
                    <h2 className="text-lg font-black text-slate-900 flex items-center gap-2">
                      <svg className="w-5 h-5 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                      Order Summary
                    </h2>
                    <p className="text-slate-400 text-xs font-bold uppercase tracking-wider mt-1">Daily totals for production</p>
                  </div>
                  <input
                    type="date"
                    value={summaryDate}
                    onChange={(e) => setSummaryDate(e.target.value)}
                    className="bg-slate-50 border-2 border-transparent focus:border-indigo-500 rounded-xl px-4 py-2 font-bold text-sm text-slate-600 outline-none transition-all cursor-pointer"
                    style={{ colorScheme: 'light' }}
                  />
                </div>

                {summaryStats.length === 0 ? (
                  <div className="text-center py-6 bg-slate-50 rounded-xl border border-dashed border-slate-200 text-slate-400 text-xs font-bold uppercase tracking-widest">No items to bake for {summaryDate}</div>
                ) : (
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                    {summaryStats.map(([name, count]) => (
                      <div key={name} className="bg-slate-50 p-3 rounded-xl flex items-center justify-between border border-slate-100 hover:border-indigo-100 transition-colors">
                        <span className="font-bold text-slate-700 text-sm truncate pr-2">{name}</span>
                        <span className="bg-white px-2.5 py-1 rounded-lg text-indigo-600 font-black text-sm shadow-sm border border-slate-50">{count}x</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              /* Order List View */
              <>
                {processedOrders.length === 0 ? (
                  <div className="py-20 text-center bg-slate-50 rounded-[2rem] border-2 border-dashed border-slate-200">
                    <div className="bg-white w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-sm">
                      <svg className="w-8 h-8 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>
                    </div>
                    <h3 className="font-bold text-slate-900">
                      {orders.length === 0 ? 'No active orders' : 'No matching orders'}
                    </h3>
                    <p className="text-slate-400 text-sm mt-1">
                      {orders.length === 0 ? 'Ready for your first cake booking' : 'Try adjusting your filters'}
                    </p>
                    {filter !== 'today' && (
                      <button onClick={() => setFilter('today')} className="mt-4 text-xs font-bold text-indigo-600 hover:underline">Show today's orders</button>
                    )}
                  </div>
                ) : (
                  <div className="space-y-4">
                    {processedOrders.map((order) => {
                      const groupStyle = customerColorMap[order.customerName?.trim()];
                      const cardClassName = `p-5 rounded-[1.5rem] border transition-all flex flex-col md:flex-row items-start gap-5 ${order.status === 'completed'
                        ? `opacity-60 ${groupStyle ? groupStyle : 'bg-slate-50/50 border-slate-100'}`
                        : `shadow-sm hover:border-indigo-200 ${groupStyle ? groupStyle : 'bg-white border-slate-100'}`
                        }`;

                      return (
                        <div
                          key={order.id}
                          className={cardClassName}
                        >
                          <div className="flex-1 flex flex-row gap-5 w-full">
                            {/* Quantity Badge - Left Side */}
                            <div className={`h-14 w-14 rounded-2xl flex items-center justify-center font-black text-lg shrink-0 ${order.status === 'completed' ? 'bg-slate-100 text-slate-400' : 'bg-indigo-50 text-indigo-600'}`}>
                              {order.quantity}x
                            </div>

                            <div className="flex-1 min-w-0">
                              {/* Item Name and Source Row */}
                              <div className="flex flex-wrap items-center gap-2 mb-1">
                                <h4 className={`font-black text-lg leading-tight ${order.status === 'completed' ? 'line-through text-slate-400' : 'text-slate-900'}`}>
                                  {order.itemName}
                                </h4>
                                {order.source && (
                                  <span className={`text-[9px] px-1.5 py-0.5 rounded font-black uppercase tracking-tighter ${order.source === 'Instagram' ? 'bg-purple-100 text-purple-600' :
                                    order.source === 'Marketplace' ? 'bg-blue-100 text-blue-600' :
                                      order.source === 'FB Page' ? 'bg-indigo-100 text-indigo-600' :
                                        'bg-slate-100 text-slate-500'
                                    }`}>
                                    {order.source}
                                  </span>
                                )}
                              </div>

                              {/* Customer Name */}
                              <div className={`text-sm font-bold mb-2 ${order.status === 'completed' ? 'text-slate-300' : 'text-slate-600'}`}>
                                {order.customerName || 'Guest'}
                              </div>

                              {/* Price and Pickup Time Row */}
                              <div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-wider">
                                <span className="text-slate-400">${order.total.toFixed(2)}</span>
                                <span className="text-slate-300 text-[10px]">•</span>
                                <span className="text-indigo-600">PICKUP: {getDayName(order.pickupDate)}, {order.pickupDate} {order.pickupTime}</span>
                              </div>

                              {/* Notes - Blue Italic */}
                              {order.notes && (
                                <div className="mt-2 text-[11px] font-medium text-indigo-500 italic">
                                  "{order.notes}"
                                </div>
                              )}
                            </div>
                          </div>

                          {/* Action Buttons - Right Side (Desktop) or Bottom (Mobile) */}
                          <div className="flex items-center gap-1 md:ml-auto mt-2 md:mt-0 self-end md:self-center w-full md:w-auto justify-end">
                            <button
                              onClick={() => handleDuplicateOrder(order)}
                              className="p-2 text-slate-300 hover:text-indigo-600 rounded-lg transition-colors"
                              title="Duplicate Order"
                            >
                              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
                            </button>
                            <button
                              onClick={() => setOrderToDelete(order.id)}
                              className="p-2 text-slate-300 hover:text-rose-500 rounded-lg transition-colors"
                              title="Delete Order"
                            >
                              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                            </button>
                            <button
                              onClick={() => handleEditOrder(order)}
                              className={`p-2 rounded-lg transition-all ${order.status === 'completed' ? 'text-slate-300 pointer-events-none' : 'text-slate-300 hover:text-indigo-600'}`}
                              title="Edit Order"
                            >
                              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg>
                            </button>
                            <button
                              onClick={() => toggleOrderStatus(order.id)}
                              className={`ml-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${order.status === 'completed' ? 'bg-slate-100 text-slate-600' : 'bg-emerald-50 text-emerald-600 hover:bg-emerald-100'}`}
                            >
                              {order.status === 'completed' ? 'Re-open' : 'Complete'}
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </>
            )}
          </div>
        ) : activeTab === 'menu' ? (
          <MenuManager
            menu={menu}
            onAdd={handleAddMenuItem}
            onRemove={handleRemoveMenuItem}
            onUpdate={handleUpdateMenuItem}
          />
        ) : (
          <SalesReports orders={orders} />
        )}
      </main>

      {/* Mobile Tab Bar */}
      <div className="md:hidden fixed bottom-8 left-8 right-8 bg-white border border-slate-100 rounded-2xl p-2 flex shadow-2xl z-50">
        <button
          onClick={() => setActiveTab('orders')}
          className={`flex-1 flex flex-col items-center py-2.5 rounded-xl transition-all ${activeTab === 'orders' ? 'bg-indigo-600 text-white' : 'text-slate-400'}`}
        >
          <svg className="w-5 h-5 mb-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>
          <span className="text-[10px] font-bold">Orders</span>
        </button>
        <button
          onClick={() => setActiveTab('menu')}
          className={`flex-1 flex flex-col items-center py-2.5 rounded-xl transition-all ${activeTab === 'menu' ? 'bg-indigo-600 text-white' : 'text-slate-400'}`}
        >
          <svg className="w-5 h-5 mb-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>
          <span className="text-[10px] font-bold">Menu</span>
        </button>
        <button
          onClick={() => setActiveTab('reports')}
          className={`flex-1 flex flex-col items-center py-2.5 rounded-xl transition-all ${activeTab === 'reports' ? 'bg-indigo-600 text-white' : 'text-slate-400'}`}
        >
          <svg className="w-5 h-5 mb-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>
          <span className="text-[10px] font-bold">Sales</span>
        </button>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  return (
    <ProtectedRoute>
      <Dashboard />
    </ProtectedRoute>
  );
};

export default App;